version: "3.8"

services:
  app_sov0002:
    build: ./app_sov0002
    container_name: app_sov0002
    ports:
      - "8001:8001"  # Exponemos solo 8001
    networks:
      - webnet
    environment:
      - SECRETO=mi_valor_secreto

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"  # Puerto p√∫blico
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_sov0002
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
